update workflows

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -10,33 +10,30 @@ env:
 
 jobs:
   check:
-    name: cargo check
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: dtolnay/rust-toolchain@stable
         with:
-          target: wasm32-wasip2 # WebAssembly target
+          target: wasm32-wasip2
           components: rustfmt
       - uses: edgee-cloud/install-edgee-cli@v0.2.0
       - run: edgee component wit
       - run: cargo check
 
   fmt:
-    name: cargo fmt
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: dtolnay/rust-toolchain@stable
         with:
-          components: rustfmt
           target: wasm32-wasip2
+          components: rustfmt
       - uses: edgee-cloud/install-edgee-cli@v0.2.0
       - run: edgee component wit
       - uses: actions-rust-lang/rustfmt@v1
 
   clippy:
-    name: clippy
     runs-on: ubuntu-latest
     permissions:
       checks: write
@@ -44,8 +41,8 @@ jobs:
       - uses: actions/checkout@v4
       - uses: dtolnay/rust-toolchain@stable
         with:
-          components: clippy
           target: wasm32-wasip2
+          components: clippy
       - uses: edgee-cloud/install-edgee-cli@v0.2.0
       - run: edgee component wit
       - uses: wearerequired/lint-action@master
@@ -53,23 +50,24 @@ jobs:
           clippy: true
 
   build:
-    name: cargo build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: dtolnay/rust-toolchain@stable
         with:
-          target: wasm32-wasip2 # WebAssembly target
+          target: wasm32-wasip2
       - uses: edgee-cloud/install-edgee-cli@v0.2.0
       - run: edgee component build
+      - name: Copy .wasm to root
+        run: cp ./target/wasm32-wasip2/release/mixpanel_component.wasm ./mixpanel_component.wasm
       - name: Verify .wasm file exists
         run: |
-          if [ ! -f "./amplitude.wasm" ]; then
-              echo "❌ Error: amplitude.wasm not found" >&2
-              exit 1
+          if [ ! -f "./mixpanel_component.wasm" ]; then
+            echo "❌ Error: mixpanel_component.wasm not found" >&2
+            exit 1
           fi
+
   test:
-    name: cargo test
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -78,10 +76,9 @@ jobs:
           target: wasm32-wasip2
       - uses: edgee-cloud/install-edgee-cli@v0.2.0
       - run: edgee component wit
-      - run: make test
+      - run: cargo test
 
   coverage:
-    name: coverage & coveralls
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
